# This is a basic workflow that is manually triggered

name: epg pull and host
permissions:
  contents: write
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: 0 12,23 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  server:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v4
    - run: wget https://epgshare01.online/epgshare01/epg_ripper_HU1.xml.gz
    - run: rm -rf epg_ripper_HU1.xml
    - run: gunzip epg_ripper_HU1.xml.gz
    - run: |
          git config --global user.name 'Zsobix'
          git config --global user.email 'zsobix@users.noreply.github.com'
          git add epg_ripper_HU1.xml
          git commit -m "epg workflow"
          git push
